name: CI
'on': push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: 'echo ${GITHUB_REF##*/}'
        id: extract_branch
   

     
