name: CI
'on': push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: 'echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT'

     
